### ISSUE TITLE
invalid PDF

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/ChunilalGandhiVidyabhavan#16]
Error in PDF file in accession number 0197.

```
0152#0197#muhurtamartanda_martandavallabhasahita-CGV-PSS-0152-0197
Started at 2018-11-09 14:06:10.047222
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\internetarchive\item.py", line 722, in upload_file
    response.raise_for_status()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Data for url: https://s3.us.archive.org/muhurtamartanda_martandavallabhasahita-CGV-PSS-0152-0197/muhurtamartanda_martandavallabhasahita-CGV-PSS-0152-0197.pdf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uploader.py", line 140, in <module>
    uploadToArchive(metadata)
  File "uploader.py", line 104, in uploadToArchive
    r = upload(identifier, {identifier+'.pdf': '../compressedPdfFiles/BOOK_NO.'+accession+'.pdf'}, metadata=metadata)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\internetarchive\api.py", line 297, in upload
    request_kwargs=request_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\internetarchive\item.py", line 860, in upload
    request_kwargs=request_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\internetarchive\item.py", line 742, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading muhurtamartanda_martandavallabhasahita-CGV-PSS-0152-0197.pdf to muhurtamartanda_martandavallabhasahita-CGV-PSS-0152-0197, Uploaded content is unacceptable. - error checking pdf file
```

**Comment by drdhaval2785** [comment]
regenerated 0181 to 0200 with help of jpgToPdf.sh lying in scannedBooks folder.
