### ISSUE TITLE
Connection forcibly closed by remote host

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/ChunilalGandhiVidyabhavan#17]
```
0188#0587#vasishthi-CGV-PSS-0188-0587
Started at 2018-11-09 15:19:33.787400
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 642, in write
    return self._sslobj.write(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uploader.py", line 140, in <module>
    uploadToArchive(metadata)
  File "uploader.py", line 104, in uploadToArchive
    r = upload(identifier, {identifier+'.pdf': '../compressedPdfFiles/BOOK_NO.'+accession+'.pdf'}, metadata=metadata)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\internetarchive\api.py", line 297, in upload
    request_kwargs=request_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\internetarchive\item.py", line 860, in upload
    request_kwargs=request_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\internetarchive\item.py", line 710, in upload_file
    **request_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\internetarchive\session.py", line 370, in send
    r = super(ArchiveSession, self).send(request, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

**Comment by drdhaval2785** [comment]
Seems to be just a temporary connection issue. Restarted from the same point without any issue.
